### ISSUE TITLE
Reproducing this work

### ISSUE THREAD

**Issue by CubicQubit** [tianlinxu312/cot-gan#4]
Hi there,

I was wondering if the original authors have run into this error
 ```tensorflow/core/grappler/optimizers/meta_optimizer.cc:561] function_optimizer failed: Invalid argument: Input 0 of node zeros_like_72 was passed float from sequential/lstm/StatefulPartitionedCall:9 incompatible with expected variant.```
```2021-10-13 18:40:24.989984: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:561] function_optimizer failed: Invalid argument: Input 0 of node zeros_like_72 was passed float from sequential/lstm/StatefulPartitionedCall:9 incompatible with expected variant.```

I got this while running python3.7.10 and installed the requirements.txt. The program still runs and outputs normally but it cannot learn the toy examples for `sines` very well. I was wondering if the above error is causing problems as I'm trying to run cotgan on some time-series data.

Training curve:
![2021-10-13 20_44_41-Window](https://user-images.githubusercontent.com/13146442/137248122-0e5fc33c-8691-413c-948f-46be02e1b3c1.png)

Real samples: Plot the first 4 dimensions for 8 samples, with increasing frequency for each dimension.
![real_sines](https://user-images.githubusercontent.com/13146442/137248080-cfd4a1c9-675c-4e0d-b6e6-f152c769f075.png)

Generated samples: It learned the range but not the frequency / seasonality
![download](https://user-images.githubusercontent.com/13146442/137250958-2c6a753e-65b8-4880-83be-aaf038086a9c.png)

Config:
```
model_params:
  name: 'cotgan'
  reg_penalty: 10
  sinkhorn_eps: 100
  sinkhorn_l: 100
  nlstm: 1
  scaling_coef: 1
  
  z_dims_t: 10
  y_dims: 10
  
  g_state_size: 256
  d_state_size: 256
  g_filter_size: 32
  d_filter_size: 32
  disc_kernel_width: 5
  gen: 'lstm'
  
  batch_norm: True
  learning_rate: 0.001
```
